//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Rhynux_/InputActionAssets/KeyboardActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeyboardActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeyboardActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyboardActions"",
    ""maps"": [
        {
            ""name"": ""Pressed"",
            ""id"": ""c4ca0624-5c30-4a73-afe5-d767bff21f9e"",
            ""actions"": [
                {
                    ""name"": ""D"",
                    ""type"": ""Button"",
                    ""id"": ""09e3f0ee-9cdc-4a49-a543-05cbd1a9e0bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""6f8b9644-efbf-4f8e-b9ef-9119a0ce7023"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""J"",
                    ""type"": ""Button"",
                    ""id"": ""f3a85b9f-315f-4d84-858a-fc9633d3cff5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""K"",
                    ""type"": ""Button"",
                    ""id"": ""0409f99a-685d-4318-8b62-56743be209e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1bf9706e-4d81-4f65-9583-799b8d63c2ad"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbc61313-df8e-4999-9998-cc0d2059878e"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c749566-e3ff-4302-8e56-ad83749279c0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""352d1f48-4d91-4010-bb01-b1dea13fad8e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Released"",
            ""id"": ""2a886ca7-1d80-45eb-95e4-ff39fe205f03"",
            ""actions"": [
                {
                    ""name"": ""D"",
                    ""type"": ""Button"",
                    ""id"": ""2199cb06-53e2-4529-b8d2-eaca4d588a32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""49fb5949-2069-43a2-93ef-1e49aa9e2769"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""J"",
                    ""type"": ""Button"",
                    ""id"": ""df563929-99f9-4486-bf7b-7e38c76c3b55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""K"",
                    ""type"": ""Button"",
                    ""id"": ""51a33477-7824-4ec7-a308-af64f4bc9567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a8e74c5f-b1ad-4fcf-9c1d-5856ca9a0eda"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""516b980e-a9bb-4816-9592-865cb46fd72a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f6bf504-681e-4da1-af3d-849b24e526b7"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""J"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4c4c2e3-66f4-49ee-8030-b31aeaff9663"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""K"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Pressed
        m_Pressed = asset.FindActionMap("Pressed", throwIfNotFound: true);
        m_Pressed_D = m_Pressed.FindAction("D", throwIfNotFound: true);
        m_Pressed_F = m_Pressed.FindAction("F", throwIfNotFound: true);
        m_Pressed_J = m_Pressed.FindAction("J", throwIfNotFound: true);
        m_Pressed_K = m_Pressed.FindAction("K", throwIfNotFound: true);
        // Released
        m_Released = asset.FindActionMap("Released", throwIfNotFound: true);
        m_Released_D = m_Released.FindAction("D", throwIfNotFound: true);
        m_Released_F = m_Released.FindAction("F", throwIfNotFound: true);
        m_Released_J = m_Released.FindAction("J", throwIfNotFound: true);
        m_Released_K = m_Released.FindAction("K", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Pressed
    private readonly InputActionMap m_Pressed;
    private List<IPressedActions> m_PressedActionsCallbackInterfaces = new List<IPressedActions>();
    private readonly InputAction m_Pressed_D;
    private readonly InputAction m_Pressed_F;
    private readonly InputAction m_Pressed_J;
    private readonly InputAction m_Pressed_K;
    public struct PressedActions
    {
        private @KeyboardActions m_Wrapper;
        public PressedActions(@KeyboardActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @D => m_Wrapper.m_Pressed_D;
        public InputAction @F => m_Wrapper.m_Pressed_F;
        public InputAction @J => m_Wrapper.m_Pressed_J;
        public InputAction @K => m_Wrapper.m_Pressed_K;
        public InputActionMap Get() { return m_Wrapper.m_Pressed; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PressedActions set) { return set.Get(); }
        public void AddCallbacks(IPressedActions instance)
        {
            if (instance == null || m_Wrapper.m_PressedActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PressedActionsCallbackInterfaces.Add(instance);
            @D.started += instance.OnD;
            @D.performed += instance.OnD;
            @D.canceled += instance.OnD;
            @F.started += instance.OnF;
            @F.performed += instance.OnF;
            @F.canceled += instance.OnF;
            @J.started += instance.OnJ;
            @J.performed += instance.OnJ;
            @J.canceled += instance.OnJ;
            @K.started += instance.OnK;
            @K.performed += instance.OnK;
            @K.canceled += instance.OnK;
        }

        private void UnregisterCallbacks(IPressedActions instance)
        {
            @D.started -= instance.OnD;
            @D.performed -= instance.OnD;
            @D.canceled -= instance.OnD;
            @F.started -= instance.OnF;
            @F.performed -= instance.OnF;
            @F.canceled -= instance.OnF;
            @J.started -= instance.OnJ;
            @J.performed -= instance.OnJ;
            @J.canceled -= instance.OnJ;
            @K.started -= instance.OnK;
            @K.performed -= instance.OnK;
            @K.canceled -= instance.OnK;
        }

        public void RemoveCallbacks(IPressedActions instance)
        {
            if (m_Wrapper.m_PressedActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPressedActions instance)
        {
            foreach (var item in m_Wrapper.m_PressedActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PressedActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PressedActions @Pressed => new PressedActions(this);

    // Released
    private readonly InputActionMap m_Released;
    private List<IReleasedActions> m_ReleasedActionsCallbackInterfaces = new List<IReleasedActions>();
    private readonly InputAction m_Released_D;
    private readonly InputAction m_Released_F;
    private readonly InputAction m_Released_J;
    private readonly InputAction m_Released_K;
    public struct ReleasedActions
    {
        private @KeyboardActions m_Wrapper;
        public ReleasedActions(@KeyboardActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @D => m_Wrapper.m_Released_D;
        public InputAction @F => m_Wrapper.m_Released_F;
        public InputAction @J => m_Wrapper.m_Released_J;
        public InputAction @K => m_Wrapper.m_Released_K;
        public InputActionMap Get() { return m_Wrapper.m_Released; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ReleasedActions set) { return set.Get(); }
        public void AddCallbacks(IReleasedActions instance)
        {
            if (instance == null || m_Wrapper.m_ReleasedActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ReleasedActionsCallbackInterfaces.Add(instance);
            @D.started += instance.OnD;
            @D.performed += instance.OnD;
            @D.canceled += instance.OnD;
            @F.started += instance.OnF;
            @F.performed += instance.OnF;
            @F.canceled += instance.OnF;
            @J.started += instance.OnJ;
            @J.performed += instance.OnJ;
            @J.canceled += instance.OnJ;
            @K.started += instance.OnK;
            @K.performed += instance.OnK;
            @K.canceled += instance.OnK;
        }

        private void UnregisterCallbacks(IReleasedActions instance)
        {
            @D.started -= instance.OnD;
            @D.performed -= instance.OnD;
            @D.canceled -= instance.OnD;
            @F.started -= instance.OnF;
            @F.performed -= instance.OnF;
            @F.canceled -= instance.OnF;
            @J.started -= instance.OnJ;
            @J.performed -= instance.OnJ;
            @J.canceled -= instance.OnJ;
            @K.started -= instance.OnK;
            @K.performed -= instance.OnK;
            @K.canceled -= instance.OnK;
        }

        public void RemoveCallbacks(IReleasedActions instance)
        {
            if (m_Wrapper.m_ReleasedActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IReleasedActions instance)
        {
            foreach (var item in m_Wrapper.m_ReleasedActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ReleasedActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ReleasedActions @Released => new ReleasedActions(this);
    public interface IPressedActions
    {
        void OnD(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnJ(InputAction.CallbackContext context);
        void OnK(InputAction.CallbackContext context);
    }
    public interface IReleasedActions
    {
        void OnD(InputAction.CallbackContext context);
        void OnF(InputAction.CallbackContext context);
        void OnJ(InputAction.CallbackContext context);
        void OnK(InputAction.CallbackContext context);
    }
}
