//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Rhynux_/InputActionAssets/Selection.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Selection: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Selection()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Selection"",
    ""maps"": [
        {
            ""name"": ""Track"",
            ""id"": ""77c31c85-1bbd-4ec7-ae26-bf0962f3ec51"",
            ""actions"": [
                {
                    ""name"": ""Track Up"",
                    ""type"": ""Button"",
                    ""id"": ""d76904a3-21ad-49d2-a104-3d44a9160309"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Track Down"",
                    ""type"": ""Button"",
                    ""id"": ""2b271d99-8e9e-4f53-9975-e3732bd72ae9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2cfcbaa-df05-4db1-a2e3-0abec17f55ba"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Track Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f987f48-564e-4764-8290-6b5421968d52"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Track Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25844b33-e7b5-48d7-b48e-b02f209e356f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Track Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16681b66-8215-430c-9bdd-b92660240516"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Track Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""357fd84f-9549-4956-8f96-f35baad6fe8a"",
            ""actions"": [
                {
                    ""name"": ""Menu Next"",
                    ""type"": ""Button"",
                    ""id"": ""fdd10126-48e0-4809-aa8a-825e78e21722"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu Back"",
                    ""type"": ""Button"",
                    ""id"": ""5199c7a2-c468-408f-ae45-4f51a7d031f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e74a1019-55e5-48fe-8065-e4d940682b10"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82aa1b72-fdbd-4cdd-bca2-4a5c36074f21"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2b1ec1e-a65b-45f5-9763-dcbcbe266571"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Next"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff4f04aa-d551-42bd-a478-5fe195f30647"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1ff4bdb1-ed64-495a-9d37-e1766dc74e74"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Track
        m_Track = asset.FindActionMap("Track", throwIfNotFound: true);
        m_Track_TrackUp = m_Track.FindAction("Track Up", throwIfNotFound: true);
        m_Track_TrackDown = m_Track.FindAction("Track Down", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_MenuNext = m_Menu.FindAction("Menu Next", throwIfNotFound: true);
        m_Menu_MenuBack = m_Menu.FindAction("Menu Back", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Track
    private readonly InputActionMap m_Track;
    private List<ITrackActions> m_TrackActionsCallbackInterfaces = new List<ITrackActions>();
    private readonly InputAction m_Track_TrackUp;
    private readonly InputAction m_Track_TrackDown;
    public struct TrackActions
    {
        private @Selection m_Wrapper;
        public TrackActions(@Selection wrapper) { m_Wrapper = wrapper; }
        public InputAction @TrackUp => m_Wrapper.m_Track_TrackUp;
        public InputAction @TrackDown => m_Wrapper.m_Track_TrackDown;
        public InputActionMap Get() { return m_Wrapper.m_Track; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TrackActions set) { return set.Get(); }
        public void AddCallbacks(ITrackActions instance)
        {
            if (instance == null || m_Wrapper.m_TrackActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TrackActionsCallbackInterfaces.Add(instance);
            @TrackUp.started += instance.OnTrackUp;
            @TrackUp.performed += instance.OnTrackUp;
            @TrackUp.canceled += instance.OnTrackUp;
            @TrackDown.started += instance.OnTrackDown;
            @TrackDown.performed += instance.OnTrackDown;
            @TrackDown.canceled += instance.OnTrackDown;
        }

        private void UnregisterCallbacks(ITrackActions instance)
        {
            @TrackUp.started -= instance.OnTrackUp;
            @TrackUp.performed -= instance.OnTrackUp;
            @TrackUp.canceled -= instance.OnTrackUp;
            @TrackDown.started -= instance.OnTrackDown;
            @TrackDown.performed -= instance.OnTrackDown;
            @TrackDown.canceled -= instance.OnTrackDown;
        }

        public void RemoveCallbacks(ITrackActions instance)
        {
            if (m_Wrapper.m_TrackActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITrackActions instance)
        {
            foreach (var item in m_Wrapper.m_TrackActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TrackActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TrackActions @Track => new TrackActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_MenuNext;
    private readonly InputAction m_Menu_MenuBack;
    public struct MenuActions
    {
        private @Selection m_Wrapper;
        public MenuActions(@Selection wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuNext => m_Wrapper.m_Menu_MenuNext;
        public InputAction @MenuBack => m_Wrapper.m_Menu_MenuBack;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @MenuNext.started += instance.OnMenuNext;
            @MenuNext.performed += instance.OnMenuNext;
            @MenuNext.canceled += instance.OnMenuNext;
            @MenuBack.started += instance.OnMenuBack;
            @MenuBack.performed += instance.OnMenuBack;
            @MenuBack.canceled += instance.OnMenuBack;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @MenuNext.started -= instance.OnMenuNext;
            @MenuNext.performed -= instance.OnMenuNext;
            @MenuNext.canceled -= instance.OnMenuNext;
            @MenuBack.started -= instance.OnMenuBack;
            @MenuBack.performed -= instance.OnMenuBack;
            @MenuBack.canceled -= instance.OnMenuBack;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface ITrackActions
    {
        void OnTrackUp(InputAction.CallbackContext context);
        void OnTrackDown(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnMenuNext(InputAction.CallbackContext context);
        void OnMenuBack(InputAction.CallbackContext context);
    }
}
