//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Rhynux_/KeyboardActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeyboardActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeyboardActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyboardActions"",
    ""maps"": [
        {
            ""name"": ""Pressed"",
            ""id"": ""c4ca0624-5c30-4a73-afe5-d767bff21f9e"",
            ""actions"": [
                {
                    ""name"": ""F"",
                    ""type"": ""Button"",
                    ""id"": ""6f8b9644-efbf-4f8e-b9ef-9119a0ce7023"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1bf9706e-4d81-4f65-9583-799b8d63c2ad"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Pressed
        m_Pressed = asset.FindActionMap("Pressed", throwIfNotFound: true);
        m_Pressed_F = m_Pressed.FindAction("F", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Pressed
    private readonly InputActionMap m_Pressed;
    private List<IPressedActions> m_PressedActionsCallbackInterfaces = new List<IPressedActions>();
    private readonly InputAction m_Pressed_F;
    public struct PressedActions
    {
        private @KeyboardActions m_Wrapper;
        public PressedActions(@KeyboardActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @F => m_Wrapper.m_Pressed_F;
        public InputActionMap Get() { return m_Wrapper.m_Pressed; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PressedActions set) { return set.Get(); }
        public void AddCallbacks(IPressedActions instance)
        {
            if (instance == null || m_Wrapper.m_PressedActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PressedActionsCallbackInterfaces.Add(instance);
            @F.started += instance.OnF;
            @F.performed += instance.OnF;
            @F.canceled += instance.OnF;
        }

        private void UnregisterCallbacks(IPressedActions instance)
        {
            @F.started -= instance.OnF;
            @F.performed -= instance.OnF;
            @F.canceled -= instance.OnF;
        }

        public void RemoveCallbacks(IPressedActions instance)
        {
            if (m_Wrapper.m_PressedActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPressedActions instance)
        {
            foreach (var item in m_Wrapper.m_PressedActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PressedActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PressedActions @Pressed => new PressedActions(this);
    public interface IPressedActions
    {
        void OnF(InputAction.CallbackContext context);
    }
}
